workflows:
  react_native_tally:
    name: React Native Tally App
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: "\${EXPO_TOKEN}" # Set this in Codemagic UI under Environment Variables
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Log in to Expo
        script: |
          npx expo login --non-interactive --username "\${EXPO_USERNAME}" --password "\${EXPO_PASSWORD}"
      - name: Build Android APK
        script: |
          npx eas build --platform android --profile preview --non-interactive
      - name: Build iOS IPA (if applicable)
        script: |
          npx eas build --platform ios --profile preview --non-interactive
    artifacts:
      - build/**/android/**/*.apk
      - build/**/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - "elarabijnr@gmail.com"
          - "kengyap@upm.edu.my"
