workflows:
  react-native-app:
    name: React Native Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_VERSION: 18
        JAVA_VERSION: 17
        EXPO_TOKEN: "your-expo-token"  # Set this in Codemagic UI for security
      groups:
        - app_credentials # Reference environment variable groups for signing
      cache:
        cache_paths:
          - ~/.npm
          - ~/.gradle/caches
          - ~/.gradle/wrapper
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android app
        script: |
          cd android && ./gradlew assembleRelease
      - name: Build iOS app
        script: |
          cd ios && pod install && xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos build
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - ios/build/**/*.ipa
    publishing:
      email:
        recipients:
          - "elarabijnr@gmail.com"
          - "kengyap@upm.edu.my"
